<?php

namespace percipiolondon\craftstaff\gql\types\elements;

use craft\gql\types\elements\Element;
use GraphQL\Type\Definition\ResolveInfo;

class Employer extends Element
{
    public function __construct(array $config)
    {
        $config['interfaces'] = [
            \percipiolondon\craftstaff\gql\interfaces\elements\Employer::getType()
        ];

        parent::__construct($config);
    }

    protected function resolve($source, $arguments, $context, ResolveInfo $resolveInfo)
    {
        return parent::resolve($source, $arguments, $context, $resolveInfo); // TODO: Change the autogenerated stub
    }
}
