<?php

namespace percipiolondon\staff\elements\db;

use craft\elements\db\ElementQuery;
use craft\helpers\Db;

class HistoryQuery extends ElementQuery
{
    public $employeeId;
    public $employerId;
    public $type;

    public function employeeId($value)
    {
        $this->employeeId = $value;
        return $this;
    }

    public function employerId($value)
    {
        $this->employerId = $value;
        return $this;
    }

    public function type($value)
    {
        $this->type = $value;
        return $this;
    }

    protected function beforePrepare(): bool
    {
        $this->joinElementTable('staff_history');

        $this->query->select([
            'staff_history.employerId',
            'staff_history.employeeId',
            'staff_history.administerId',
            'staff_history.message',
            'staff_history.data',
            'staff_history.type',
        ]);

        if ($this->employeeId) {
            $this->subQuery->andWhere(Db::parseParam('staff_history.employeeId', $this->employeeId));
        }

        if ($this->employerId) {
            $this->subQuery->andWhere(Db::parseParam('staff_history.employerId', $this->employerId));
        }

        if ($this->type) {
            $this->subQuery->andWhere(Db::parseParam('staff_history.type', $this->type));
        }

        return parent::beforePrepare(); // TODO: Change the autogenerated stub
    }
}