<?php
/**
 * staff-management plugin for Craft CMS 3.x
 *
 * Craft Staff Management provides an HR solution for payroll and benefits
 *
 * @link      http://percipio.london
 * @copyright Copyright (c) 2021 Percipio
 */

namespace percipiolondon\staff\elements;

use Craft;
use DateTime;
use craft\base\Element;
use craft\elements\db\ElementQueryInterface;
use percipiolondon\staff\elements\db\RequestQuery;
use percipiolondon\staff\helpers\requests\CreateAddressRequest;
use percipiolondon\staff\helpers\requests\CreatePersonalDetailsRequest;
use percipiolondon\staff\records\Requests;

/**
 * Request Element
 *
 * Element is the base class for classes representing elements in terms of objects.
 *
 */
class Request extends Element
{
    /**
     * @var DateTime|null
     */
    public ?DateTime $dateAdministered = null;
    /**
     * @var int|null
     */
    public ?int $employerId = null;
    /**
     * @var int|null
     */
    public ?int $employeeId = null;
    /**
     * @var int|null
     */
    public ?int $administerId = null;
    /**
     * @var string|null
     */
    public ?string $data = null;
    /**
     * @var string|null
     */
    public ?string $type = null;
    /**
     * @var string|null
     */
    public ?string $status = null;
    /**
     * @var string|null
     */
    public ?string $note = null;

    /**
     * @return string
     */
    public static function displayName(): string
    {
        return Craft::t('staff-management', 'Request');
    }

    /**
     * @return string
     */
    public static function lowerDisplayName(): string
    {
        return Craft::t('staff-management', 'request');
    }

    /**
     * @return string
     */
    public static function pluralDisplayName(): string
    {
        return Craft::t('staff-management', 'Requests');
    }

    /**
     * @return string
     */
    public static function pluralLowerDisplayName(): string
    {
        return Craft::t('staff-management', 'requests');
    }

    public function defineRules(): array
    {
        $rules = parent::defineRules();
        $rules[] = [['employerId', 'employeeId', 'type'], 'required'];

        return $rules;
    }

    /**
     * @return ElementQueryInterface
     */
    public static function find(): ElementQueryInterface
    {
        return new RequestQuery(static::class);
    }

    // Indexes, etc.
    // -------------------------------------------------------------------------

    public static function gqlTypeNameByContext($context): string
    {
        return 'Request';
    }

    /**
     * @inheritdoc
     */
    public function getGqlTypeName(): string
    {
        return static::gqlTypeNameByContext($this);
    }

    /**
     * @inheritdoc
     */
    public static function gqlMutationNameByContext(mixed $context): string
    {
        return 'CreateMutation';
    }

    /**
     * @param bool $isNew
     */
    public function afterSave(bool $isNew): void
    {
        if (!$this->propagating) {
            $this->_saveRecord($isNew);
        }

        parent::afterSave($isNew); // TODO: Change the autogenerated stub
    }

    /**
     * @param bool $isNew
     */
    private function _saveRecord(bool $isNew): void
    {
        try {
            $helper = null;
            $request = null;

            if(!$isNew) {
                $request = Requests::findOne($this->id);

                if(!$request) {
                    throw new \Exception('Invalid request ID: ' . $this->id);
                }
            } else {
                $request = new Requests();
                $request->id = $this->id;
            }

            // convert form submission to saved personal data
            switch ($this->type) {
                case 'address':
                    $helper = new CreateAddressRequest();
                    break;
                case 'personal_details':
                    $helper = new CreatePersonalDetailsRequest();
                    break;
            }

            $request->id = $this->id;
            $request->employerId = $this->employerId;
            $request->employeeId = $this->employeeId;
            $request->type = $this->type;
            $request->status = $this->status ?? 'pending';
            $request->data = $helper ? $helper->create($this->data, $this->employeeId) : null;

            $request->save();
        } catch (\Exception $e) {
            Craft::error($e->getMessage(), __METHOD__);
        }
    }
}