<?php

namespace percipiolondon\staff\gql\interfaces\elements;

use craft\gql\GqlEntityRegistry;
use craft\gql\interfaces\Element;
use craft\gql\TypeManager;
use GraphQL\Type\Definition\InterfaceType;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;
use percipiolondon\staff\gql\types\generators\HistoryGenerator;
use percipiolondon\staff\elements\History as HistoryElement;

class History extends Element
{
    public static function getTypeGenerator(): string
    {
        return parent::getTypeGenerator(); // TODO: Change the autogenerated stub
    }

    public static function getType($fields = null): Type
    {
        if ($type = GqlEntityRegistry::getEntity(self::getName())) {
            return $type;
        }

        $type = GqlEntityRegistry::createEntity(self::getName(), new InterfaceType([
            'name' => static::getName(),
            'fields' => self::class . '::getFieldDefinitions',
            'description' => 'This is the interface implemented by all history entries.',
            'resolveType' => function(HistoryElement $value) {
                return $value->getGqlTypeName();
            },
        ]));

        HistoryGenerator::generateTypes();

        return $type;
    }

    /**
     * @inheritdoc
     */
    public static function getName(): string
    {
        return 'HistoryInterface';
    }

    /**
     * @inheritdoc
     */
    public static function getFieldDefinitions(): array
    {
        $parentFields = parent::getFieldDefinitions();

        $fields = [
            'employerId' => [
                'name' => 'employerId',
                'type' => Type::int(),
                'description' => 'Employer id',
            ],
            'employeeId' => [
                'name' => 'employeeId',
                'type' => Type::int(),
                'description' => 'Employee id',
            ],
            'administerId' => [
                'name' => 'administerId',
                'type' => Type::int(),
                'description' => 'Administer id',
            ],
            'message' => [
                'name' => 'message',
                'type' => Type::string(),
                'description' => 'Message',
                'resolve' => function ($source, array $arguments, $context, ResolveInfo $resolveInfo) {
                    //pass the translation 'en' (hardcoded, can be an argument in the future)
                    return \Craft::t('staff-management', $source->message, 'en');
                }
            ],
            'data' => [
                'name' => 'data',
                'type' => Type::string(),
                'description' => 'Message',
            ],
            'type' => [
                'name' => 'type',
                'type' => Type::string(),
                'description' => 'Type',
            ],
        ];

        return TypeManager::prepareFieldDefinitions(array_merge($parentFields, $fields), self::getName());
    }
}